### ISSUE TITLE
Debugger times out if shell startup is "slow"

### ISSUE THREAD

**Issue by marcm-ml** [microsoft/debugpy#1579]
## Environment data

- debugpy version: v2024.6.0
- OS and version: macos 14.4.1
- Python version (& distribution if applicable, e.g. Anaconda): 3.10 CPython
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Debugger never starts and shows "timeout" error window.
In the terminal output you can see that the debugger  command has been "pasted"/send to the terminal but the terminal was not ready yet. Hence, the command is discarded.
Its very similar to the issue described here: https://github.com/microsoft/vscode-js-debug/issues/1642

## Expected  behavior

Debugger waits for terminal to finish and then sends the command to the terminal.

## Steps to reproduce:
1. add a slow command to shell startup, e.g. "sleep 120" to ~/.zshrc or ~/.bashrc
2. start any debug session with debugpy 
3. debugger will timeout

## Background:
I have a zshrc setup that includes some startup scripts which usually take ~0.5-3 seconds. I've never found a satisfying workaround for this and many of the suggested solutions in the Issues in this repo never worked for me.

## Current Workaround:
Currently, I am using the setting which works well enough for me but I wish this extension/debugger would support the same solution as https://github.com/microsoft/vscode-js-debug/issues/1642.

Here is the link to the vscode docs: https://code.visualstudio.com/docs/terminal/profiles#_configuring-the-taskdebug-profile
and here is the setting for me:
```json
{ 
  "terminal.integrated.automationProfile.osx": {
    "path": "bash",
  },
}
```

**Comment by gramster** [comment]
@karthiknadig is this something that should be fixed in the debugger extension? See the fix for typescript for reference.

**Comment by karthiknadig** [comment]
We need to see which point fails. If it is the run-in-terminal DAP to client request that takes long then this needs to be handled in VS Code core. If it is the attach to process or one of the other attach scenarios then it is `debugpy`.

@marcm-ml As a workaround, can you try this feature that we added to the debugger? Here you open a terminal, it can take as long as it needs because you can launch the debugger from that terminal itself. It is experimental, try it and let us know https://devblogs.microsoft.com/python/python-in-visual-studio-code-february-2025-release/#no-config-debugging

**Comment by marcm-ml** [comment]
Thanks, the suggested approach works well and is currently my favourite approach when debugging in vscode! 

On a side note, for some reason vscode injects a different debugpy in my venv which overrides the debugypy bundled into vscode. I am using uv to manage my envs. I don't have any dependency or directly depend on debugpy in my pyproject.toml. My workaround is to use the full path to the bundled debugpy which is not ideal but good enough. Any suggestions on that?

**Comment by mwdiers** [comment]
This is still a problem in 1.99.3. If using integratedTerminal, the first time I launch a session, it times out. Thereafter it no longer times out. It does seem to be sending the command before the terminal is ready on first launch.

On first run, the internal terminal shows a truncated run command ending in a percent sign:

```/usr/bin/env /Users/xxxxxx/xxxxxxxxxxxxxx/x%```

On a second run, the debugger terminal window is reused, and the entire command is shown and executes properly:

```
cd /Users/xxxxxx/xxxxxxxxxxxxxx/xxxxxxxxx ; /usr/bin/env /Users/xxxxxx/xxxxxxxxxxxxxx/xxxxxxxxx/.venv/bin/python /Users/xxxxxxx/.vscode-oss/extensions/ms-python.debugpy-2025.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher 56358 – Users/xxxxxx/xxxxxxxxxxxxxx/xxxxxxxxx/manage.py runserver
```

**Comment by Liu-Ya** [comment]
same problem with WSL2
vscode：1.115.0
Python Debugger：2025.18.0

> source /home/liuya/projects/ynx_stu_api/.venv/bin/activate                                                                           
❯  source /home/liuya/projects/ynx_stu_ap /usr/bin/env /home/liuya/projects/ynx_stu_api/.venv/bin/python /home/liuya/.vscode-server/extensions/ms-python.debugpy-2025.18.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 47705 -- /home/liuya/projects/ynx_stu_api/cms/manage.py runserver 0.0.0.0:3060
source: no such file or directory: /home/liuya/projects/ynx_stu_ap

one more time

> cd /home/liuya/projects/ynx_stu_api ; /usr/bin/env /home/liuya/projects/ynx_stu_api/.venv/bin/python /home/liuya/.vscode-server/extensions/ms-python.debugpy-2025.18.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 48193 -- /home/liuya/projects/ynx_stu_api/cms/manage.py runserver 0.0.0.0:3060
Performing system checks...
> 
> System check identified no issues (0 silenced).
