### ISSUE TITLE
Debug console cuts last line of pandas dataframe

### ISSUE THREAD

**Issue by ghuname** [microsoft/debugpy#832]
Issue Type: <b>Bug</b>

1. put this code in main.py
```
import pandas as pd

df = pd.DataFrame(
    {
        'A': [1, 2, 3, 4],
        'B': ['x', 'y', 'z', 'w']
    }
)

print(df)

pass
```
2. set a breakpoint on line with "pass"
3. start debugging main.py
4. notice in output 4 rows (0-3):
```
   A  B
0  1  x
1  2  y
2  3  z
3  4  w
```
5. go to debug console and enter df <enter>, last row is missing (only 0-2):
```
df
   A  B
0  1  x
1  2  y
2  3  z
```

Debug should show last row of the dataframe.

Extension version: 2021.12.1559732655
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

**Comment by ghuname** [comment]
Is there anything new?

**Comment by luabud** [comment]
@ghuname Apologies for the delay again!

I am not able to reproduce this issue, when I try the same sample you did this is what I see:

![image](https://user-images.githubusercontent.com/45497113/153957988-e3d3e84d-1b51-43b5-b34b-3b031cb0286a.png)

Do you have the latest version of the Python extension installed (v 2022.0.1814523869)?

![image](https://user-images.githubusercontent.com/45497113/153958102-50f76ed0-abef-4a4f-80f2-c69f5362c69f.png)

**Comment by ghuname** [comment]
Hi @luabud,

I have just took a screen shoot:

![image](https://user-images.githubusercontent.com/15207713/153998812-135c776e-f27b-4235-ad5a-8030f71c07f8.png)

Please execute "df <enter>" several times in order to fill whole debug console output panel with text.
When debug console's output panel is filled with output to the bottom and you execute "df" again", dataframe's last line is missing.
I also noticed that I can scroll with mouse wheel this last output line marked with ">" from left, and than the dataframe's last line shows up. If I printsomething in debug window now, in order to push current output up, I can see all dataframe's lines.
Looks like it is a scrolling problem. 

Anyway, it is very inconvenient if you have to execute "df" and than scroll its output line with the mouse in order to see df's last line.
The version from picture is v2022.0.1814523869.

**Comment by karthiknadig** [comment]
@luabud That seems to be a UI issue. This should be moved to VS Code

**Comment by ghuname** [comment]
I noticed similar behavior with big dictionaries as well.

**Comment by luabud** [comment]
@ghuname thanks for the context! for visualizing data frames it may be better to use the data viewer when debugging. This page has more instructions on how to use it: https://github.com/microsoft/debugpy/wiki/FAQ#i-dont-see-my-whole-dictionarydataframe-in-the-variable-pane

**Comment by ghuname** [comment]
DataViewer is not functional. For example, it can be only inside of the chosen panel, you cannot have it in the full screen.
Also, all column widths are the same, which is rubbish.
If you make certain column wider and than press refresh button, columns widths are equal again...
Current DataViewer is not usable for serious usage.


What I have reported here for data frames stays for big dictionaries as well, so this is not related only to dataframes.

**Comment by zljubisic** [comment]
@ghuname is right. Look at this picture:

![image](https://user-images.githubusercontent.com/67708897/154643712-6ec24ace-df4d-4332-b858-efb0981c699b.png)


Execution of `cell_pdf_indices_df.query("datetime_id == '2021-09-30 07:00:00'")` shows only two rows, but not the last one. Scrolling doesn't help here.

If I execute `print(cell_pdf_indices_df.query("datetime_id == '2021-09-30 07:00:00'"))` in debug console, I will get all three lines.
It is better not to show anything than dataframe with no last row.

**Comment by fabioz** [comment]
@zljubisic can you provide:

- sample code to reproduce
- screenshot where it's not working
- debugger logs for the use-case where screenshots were provided

From what I can tell, things are correct regarding the debugger, and this is an UI issue in VSCode (in which case this isn't fixable in `debugpy` and should be reported to VSCode itself), but to be 100% certain, please provide the info above.

To collect debugger logs:

* Run the command `Extensions: Open Extensions Folder`
* Locate the Python extension directory, typically of the form `ms-python.python-2022.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

p.s.: Usability issues in the data viewer should probably be reported to: https://github.com/microsoft/vscode-jupyter

**Comment by fabioz** [comment]
I'm closing this issue as the messages from `debugpy` seem to be all correct for me from what I could see (in which case it'd point to being an issue in the VSCode UI as there's not much we can do in `debugpy` to fix the `VSCode` UI).

As a note, I couldn't reproduce the problem either (after trying many different things and scenario) in VSCode `1.64.2` (so, it's possible that this is already fixed in the latest VSCode).

**Comment by zljubisic** [comment]
I have just tried example from @ghuname in 1.65.2 and I got the same error.
Just put several times "df <enter>" in debug console.
So it is not solved.

**Comment by karthiknadig** [comment]
Transferring this to VS code for further investigation.
