### ISSUE TITLE
In conda environment, breakpoints in pytest cannot be hit.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/debugpy#946]
## Environment data

Build of Visual Studio Code - Insiders: 1.68.0-insider(user setup) 
Build of python-Pre-Release: v2022.7.11511005 
Build of jupyter-Pre-Release: v2022.5.1001532360 
Build of pylance: v2022.5.3 
Build of jupyter Notebook Renderers: v1.0.8 
Build of jupyter Keymap: v1.0.0 

![image](https://user-images.githubusercontent.com/82852072/171357970-96fab836-d2e8-4110-88cc-11dbb4147548.png)

## Steps to reproduce:
1. Launch VSC and create python file named pytest_test.py
( Note: Select **conda** environment)

2. Enter below code:
```
def test_passing():
    assert 42 == 42
def test_failure():
    assert 42 == -13
```
3. Run tests with pytest framework.
```"python.testing.pytestEnabled": true```
4. Set breakpoint and 'Debug Test'.

## Expected behavior

Breakpoint should be hit.

## Actual behavior

Breakpoint can not be hit.

![fail_to](https://user-images.githubusercontent.com/82852072/171362283-36c77f0c-b69f-410f-9c23-def4e889ae66.gif)

## Logs

<details>

<summary><code>DEBUG CONSOLE</code> 
</summary>

<p>

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\vyizh12\.vscode-insiders\extensions\ms-python.python-2022.7.11511005\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\vyizh12\.vscode-insiders\extensions\ms-python.python-2022.7.11511005\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\vyizh12\.vscode-insiders\extensions\ms-python.python-2022.7.11511005\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\vyizh12\.vscode-insiders\extensions\ms-python.python-2022.7.11511005\pythonFiles\testlauncher.py", line 44, in <module>
    run(cwd, testRunner, args)
  File "c:\Users\vyizh12\.vscode-insiders\extensions\ms-python.python-2022.7.11511005\pythonFiles\testlauncher.py", line 36, in run
    pytest.main(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\ProgramData\Anaconda3\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anyio\__init__.py", line 90, in <module>
    from ._core._sockets import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anyio\_core\_sockets.py", line 2, in <module>
    import ssl
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
```

</p>
</details>

Extension version: 2022.7.11511005
VS Code version: Code - Insiders 1.68.0-insider (acb156d6fb0dc451f427748d5f68774f17cc96fd, 2022-05-31T05:17:04.479Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (4 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (9.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by fabioz** [comment]
@ttSpace I'm not exactly sure why it's not hitting the breakpoint in this case. It could be due to the file location (it could be that it's being considered library code and not user code depending on where it's located).

Can you try running with:

`"justMyCode": false`

Something as:

```
{
    "name": "Debug Tests",
    "type": "python",
    "purpose": ["debug-test"],
    "console": "integratedTerminal",
    "justMyCode": false
}
```

To know whether it makes any difference?

If it still doesn't work, please provide the logging for this.

i.e.: 

* Run the command `Extensions: Open Extensions Folder`
* Locate the Python extension directory, typically of the form `ms-python.python-2022.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting `"logToFile": true`, see below:

```
{
    "name": "Debug Tests",
    "type": "python",
    "purpose": ["debug-test"],
    "console": "integratedTerminal",
    "logToFile": true,
    "justMyCode": false
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by fabioz** [comment]
As a note, I think that the error related to pytest failing when doing its module rewriting isn't related, but you probably want to fix that too just to make sure.

The error there says:

```
File "C:\ProgramData\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
```

This usually means that your environment isn't properly activated (the issue being that your `PATH` is not including the directories `Library/bin` and `DLLs`).

**Comment by ttSpace** [comment]
@fabioz  After setting this up, I get these debug*.log files. BTW, I still get this error ```ImportError: DLL load failed while importing _ssl: The specified module could not be found.```after adding ```Library/bin``` and ```DLLs ```to environment variables.

![image](https://user-images.githubusercontent.com/82852072/172308065-97527d4d-cee9-44ea-a368-82d2f1ca02e5.png)

[log.zip](https://github.com/microsoft/debugpy/files/8850483/log.zip)

**Comment by fabioz** [comment]
From looking at the logs, the file you're running (`c:\\Users\\wangjun\\Downloads\\Test3\\pytest_test.py`) doesn't even appear on the tracing (so, that's probably the reason why it doesn't hit the breakpoint).

There's another (unrelated) problem:

> FileNotFoundError: Could not find module 'c:\Users\wangjun\.vscode-insiders\extensions\ms-python.python-2022.7.11571005\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_attach_to_process\attach_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

This could give you issues to debug other threads and attach to process wouldn't work. I think the usual culprit for this file missing is some virus-scanner detecting this file an removing it (because it has code to attach to another process debuggers can flag it as a virus, but this is an issue in the virus scanner, and can't be solved by debugpy).

So, I guess that when the import fails due to the `_ssl` issue it stops running and doesn't really execute your test (you can validate this by putting some `print` there and checking if it prints what you wanted).

I'm not sure you can use the `%` for the environment variables... Also, in general, you should activate your conda environment and it should take care of the `PATH` variable instead of having to set it in the system.

**Comment by ttSpace** [comment]
<details>
<p>

```
Build of Visual Studio Code - Insiders: 1.68.0-insider(user setup)
Build of python-Pre-Release: v2022.7.11591004
Build of jupyter-Pre-Release: v2022.6.1001611018
Build of pylance-Pre-Release: v2022.6.11
Build of jupyter Notebook Renderers: v1.0.8
Build of jupyter Keymap: v1.0.0
```

</p>
</details>

 I failed to activate my conda env.

![image](https://user-images.githubusercontent.com/82852072/172750693-d051a468-c95c-4aa5-b604-d26808cce54c.png)

## Logs

<details>

<summary><code>DEBUG CONSOLE</code> 
</summary>

<p>

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2022.7.11591004\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2022.7.11591004\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2022.7.11591004\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2022.7.11591004\pythonFiles\testlauncher.py", line 44, in <module>
    run(cwd, testRunner, args)
  File "c:\Users\vting\.vscode-insiders\extensions\ms-python.python-2022.7.11591004\pythonFiles\testlauncher.py", line 36, in run
    pytest.main(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1187, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\ProgramData\Anaconda3\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\ProgramData\Anaconda3\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anyio\__init__.py", line 90, in <module>
    from ._core._sockets import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anyio\_core\_sockets.py", line 2, in <module>
    import ssl
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
```

</p>
</details>

**Comment by fabioz** [comment]
@ttSpace have you tried putting `conda` on the path?

**Comment by ttSpace** [comment]
@fabioz I added the environment variable of conda, but there is still a problem, is there any other setting I missed?

**Comment by int19h** [comment]
Conda activation is not actually done by conda.exe on Windows; it registers `conda` as an alias instead, and that alias is what does all the work. It does, however, mean that you need to initialize conda for every supported shell before it can activate that shell by running `conda init`. If I remember correctly, Conda offers to do so when it is installed, but I don't remember if it covers Powershell or only cmd.exe.

Anyway, try running `conda init powershell` first and see if that enables activation.

**Comment by ttSpace** [comment]
<details>
<p>

```
Build of Visual Studio Code - Insiders: 1.70.0-insider(user setup) 
Build of python-Pre-Release: v2022.11.12011103 
Build of jupyter-Pre-Release: v2022.7.1002031159 
Build of pylance-Pre-Release: v2022.7.41 
Build of jupyter Notebook Renderers: v1.0.9 
Build of jupyter Keymap: v1.0.0 
```

</p>
</details>

@int19h I try running ```conda init powershell``` and still failed.

![image](https://user-images.githubusercontent.com/82852072/180154238-2d6ffdb5-e534-4374-ae09-ac814d46afe3.png)

**Comment by fabioz** [comment]
@ttSpace the error says that `conda` is not on the `PATH`, so, you either need to put it in the `PATH` or you need to call it passing the full path.

**Comment by ttSpace** [comment]
<details>
<p>

```
Build of Visual Studio Code - Insiders: 1.70.0-insider(user setup) 
Build of python-Pre-Release: v2022.11.12031009
Build of jupyter-Pre-Release: v2022.7.1002051049
Build of pylance-Pre-Release: v2022.7.41 
Build of jupyter Notebook Renderers: v1.0.9 
Build of jupyter Keymap: v1.0.0 
```

</p>
</details>

@fabioz @int19h  Thanks! In toady's build, after setting conda on the path and runing ```conda init powershell```. The breakpoint was hit successfully.

![image](https://user-images.githubusercontent.com/82852072/180722438-398a78c5-fa49-4d23-a33c-96081302e883.png)

## Logs

<details>

<summary><code>TERMINAL</code> 
</summary>

<p>

```
PS C:\Users\vting\Downloads\Folder1> conda activate base

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.       
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


PS C:\Users\vting\Downloads\Folder1> conda init powershell
no change     C:\ProgramData\Anaconda3\Scripts\conda.exe
no change     C:\ProgramData\Anaconda3\Scripts\conda-env.exe
no change     C:\ProgramData\Anaconda3\Scripts\conda-script.py
no change     C:\ProgramData\Anaconda3\Scripts\conda-env-script.py
no change     C:\ProgramData\Anaconda3\condabin\conda.bat
no change     C:\ProgramData\Anaconda3\Library\bin\conda.bat
no change     C:\ProgramData\Anaconda3\condabin\_conda_activate.bat
no change     C:\ProgramData\Anaconda3\condabin\rename_tmp.bat
no change     C:\ProgramData\Anaconda3\condabin\conda_auto_activate.bat
no change     C:\ProgramData\Anaconda3\condabin\conda_hook.bat
no change     C:\ProgramData\Anaconda3\Scripts\activate.bat
no change     C:\ProgramData\Anaconda3\condabin\activate.bat
no change     C:\ProgramData\Anaconda3\condabin\deactivate.bat
modified      C:\ProgramData\Anaconda3\Scripts\activate
modified      C:\ProgramData\Anaconda3\etc\profile.d\conda.sh
modified      C:\ProgramData\Anaconda3\etc\fish\conf.d\conda.fish
no change     C:\ProgramData\Anaconda3\shell\condabin\Conda.psm1
modified      C:\ProgramData\Anaconda3\shell\condabin\conda-hook.ps1
no change     C:\ProgramData\Anaconda3\Lib\site-packages\xontrib\conda.xsh
modified      C:\ProgramData\Anaconda3\etc\profile.d\conda.csh
modified      C:\Users\vting\Documents\WindowsPowerShell\profile.ps1

==> For changes to take effect, close and re-open your current shell. <==
```

</p>
</details>

**Comment by fabioz** [comment]
Great that it's working now ;)
